---

- hosts: only_server
  become: true
  tasks:

  - name: Adding Apache and Php
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Try running commands
    command: ./sample/element.sh
      
