---

- hosts: all
  become: true
  pre_tasks: 
  
  - name: install updates
    tags: always
    apt: 
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  gather_facts: no
  roles:
    - base

- hosts: only_server
  become: true
  gather_facts: no
  roles:
    - only_server

- hosts: workstations
  become: true
  gather_facts: no
  roles:
    - workstations

