---
- hosts: all
  become: true
  tasks: 
  
  - name: install updates
    tags: always
    apt: 
      upgrade: dist
      update_cache: yes
    
- hosts: only_server
  become: true
  tasks:

  - name: Adding Apache and Php
    tags: apache,php
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: Adding mariadb package  
    tags: mariadb,db
    apt:
      name: mariadb-server
      state: latest


  - name: change email for admin on a config file
    tags: apache,httpd
    lineinfile:
      path: /var/www/html/index.html
      regexp: 'Waw ang Galing!'
      line: <h1> subra kana lods </h1>
    register: apache2t 
  
  - name: restart apache2
    tags: apache2,apache
    service:
      name: apache2
      state: restarted
    when: apache2t.changed    


  - name: start httpd
    tags: apache,apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
        name: unzip

  - name: install terraform
    unarchive: 
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


